# Generated by Django 4.2.7 on 2023-11-21 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WoodWork', '0006_articulo_precio_art'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='Precio_art',
            new_name='precio_art',
        ),
    ]
