# Generated by Django 4.2.7 on 2023-11-18 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_art', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('horas', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Madera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=10)),
                ('tipos', models.CharField(choices=[('Tropicales', 'Tropicales'), ('Tratadas', 'Tratadas'), ('Frondosas', 'Frondosas'), ('Coniferas', 'Coniferas')], max_length=100)),
                ('modelo', models.CharField(choices=[('Ebano', 'Ebano'), ('Caoba', 'Caoba'), ('Palisandro', 'Palisandro'), ('Zebrano', 'Zebrano'), ('Traviesas', 'Traviesas'), ('Vigas Tratadas', 'Tratadas'), ('Palos Cilindricos', 'Palos Cilindricos'), ('Liston', 'Liston'), ('Roble Rojo Flas', 'Roble Rojo Flas'), ('Roble Blanco Flas', 'Roble Blanco Flas'), ('Frondoso', 'Frondoso'), ('Circular Iroko', 'Circular Iroko'), ('Circulas Castaño', 'Circulas Castaño'), ('Olmo Flitches', 'Olmo Flitches'), ('Haya Vaporizada', 'Haya Vaporizada'), ('Fresno Flas', 'Fresno Flas'), ('Castaño FLitches', 'Castaño FLitches'), ('Alerce', 'Alerce'), ('Pino', 'Pino'), ('Pino Amarillo', 'Pino Amarillo')], max_length=200)),
                ('tamano', models.DecimalField(decimal_places=2, max_digits=6)),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='foto')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('precio_final', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('articulos', models.ManyToManyField(to='WoodWork.articulo')),
                ('dni_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DNI_clientes', to='WoodWork.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='madera_usada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usada', to='WoodWork.madera'),
        ),
    ]
