# Generated by Django 4.2.7 on 2023-11-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WoodWork', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuesto',
            name='fecha_entrega',
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
